name: Deploy

on: 
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: set AWS, BFF and Algolia Keys to environment
      env:
        GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID}}
        GATSBY_ALGOLIA_SEARCH_KEY: ${{secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
        ALGOLIA_ADMIN_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        DIST_ID: ${{secrets.DIST_ID}}
        MUNCHKIN_ID: ${{ secrets.MUNCHKIN_ID}}
        BFF_BLOG_URL: ${{ secrets.BFF_BLOG_URL }}
        BFF_EVENTS_URL: ${{ secrets.BFF_EVENTS_URL }}
        BFF_PING_WEBHOOK_URL: $ {{ secrets.BFF_PING_WEBHOOK_URL }}
        RELIC_ACCOUNT_ID: ${{ secrets.RELIC_ACCOUNT_ID }}
        RELIC_TRUST_KEY: ${{ secrets.RELIC_TRUST_KEY }}
        RELIC_LICENSE_KEY: ${{ secrets.RELIC_LICENSE_KEY }}
        RELIC_PRODUCTION_AGENT_ID: ${{ secrets.RELIC_PRODUCTION_AGENT_ID }}
        RELIC_PRODUCTION_APPLICATION_ID: ${{ secrets.RELIC_PRODUCTION_APPLICATION_ID }}

      run: |
        npm install
        npm run clean
        npm run build:dev && node_modules/s3-deploy/bin/s3-deploy './public/**' --cwd './public/' --bucket postman-learning-center-beta --deleteRemoved --distId $DIST_ID --invalidate '/*'



    
